=== LemmyKilmister/-LND2017/Proyecto2/Proyecto_XML/XSDPROYECTO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!--DEFINICION DE ELEMENTOS COMPUESTOS-->
<xs:element name="registro">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="datosempresario"/>
       <xs:element ref="empresa"/>
       <xs:element ref="datosempresario"/>
       <xs:element ref="empresa"/>
     </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="datosempresario">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="nombre"/>
       <xs:element ref="edad"/>
       <xs:element ref="pais" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="lugarNacimiento" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dni" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
     <xs:attribute name="ISBN"/>
   </xs:complexType>
</xs:element>
<xs:element name="empresa">
  <xs:complexType>
   <xs:sequence>
     <xs:element ref="nombreEmpresa"/>
     <xs:element ref="direccion"/>
     <xs:element ref="tipoEstablecimiento"/>
     <xs:element ref="antiguedad"/>
     <xs:element ref="Nempleados"/>
     <xs:element ref="ganancia"/>
     <xs:element ref="licencias" maxOccurs="unbounded"/>
     <xs:element ref="medidasPrevencion"/>
     <xs:element ref="Empleados"/>
     <xs:element ref="impuestos"/>
     <xs:element ref="socios" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="licencias">
<xs:complexType>
   <xs:sequence>
     <xs:element ref="licencia" minOccurs="0" maxOccurs= "10"/>
   </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="medidasPrevencion">
<xs:complexType>
   <xs:sequence>
     <xs:element ref="medida" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Empleados">
<xs:complexType>
   <xs:sequence>
   <xs:element ref="empleado"  maxOccurs="unbounded"/>
   </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="empleado">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="nombreEmpleado" minOccurs="1" maxOccurs="unbounded"/>
       <xs:element ref="HorasTrabajadas" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="edad" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="lugarNacimiento" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="tipoContrato" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="impuestos">
   <xs:complexType>
     <xs:sequence>
     <xs:element ref="tipoImpuesto"/>
     </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="socios">
   <xs:complexType>
      <xs:sequence>
        <xs:element ref="socio" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="socio">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="nombreSocio" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="edad" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="porcentajeRetribuido" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="lugarNacimiento" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dni" minOccurs="0" maxOccurs="unbounded"/>
       </xs:sequence>
   </xs:complexType>
</xs:element>
<!-- DEFINICION DE ELEMENTOS SIMPLES-->
<xs:element name="nombre">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="edad">
 <xs:simpleType>
  <xs:restriction base='xs:integer'>
    <xs:maxExclusive value='120'/>
    <xs:minExclusive value="12"/>
  </xs:restriction>
 </xs:simpleType>
</xs:element>
<xs:element name="pais">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="45"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="lugarNacimiento">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="dni">
<xs:simpleType>
   <xs:restriction base="xs:string">
     <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][a-z]"/>
   </xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="nombreEmpresa" type="xs:string"/>
<xs:element name="direccion">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="45"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="tipoEstablecimiento">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="Nempleados">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="ganancia">
  <xs:simpleType>
    <xs:restriction base="xs:float">
      <xs:minExclusive value="700"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="licencia" type="xs:string"/>
<xs:element name="medida" type="xs:string"/>
<xs:element name="nombreEmpleado">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name='HorasTrabajadas'>
 <xs:simpleType>
  <xs:restriction base='xs:decimal'>
    <xs:fractionDigits value='2'/>
  </xs:restriction>
 </xs:simpleType>
</xs:element>
<xs:element name="tipoContrato">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Parcial"/>
      <xs:enumeration value="Indefinido"/>
      <xs:enumeration value="Temporal"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="tipoImpuesto">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="45"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="nombreSocio">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="porcentajeRetribuido">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:maxExclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="antiguedad" type="xs:string"/>
</xs:schema>

=== LemmyKilmister/-LND2017/Proyecto2/Proyecto_XML/XML_PROYECTO.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDPROYECTO.xsd">
  <datosempresario ISBN="3456739">
    <nombre>David</nombre>
    <edad>20</edad>
    <pais>España</pais>
    <lugarNacimiento>Murcia</lugarNacimiento>
    <dni>76547383j</dni>
  </datosempresario>
  <empresa>
    <nombreEmpresa>American</nombreEmpresa>
    <direccion>calle general</direccion>
    <tipoEstablecimiento>comida rapida</tipoEstablecimiento>
    <antiguedad>20 años</antiguedad>
    <Nempleados>5</Nempleados>
    <ganancia>3700</ganancia> 
    <licencias>
      <licencia>Apertura</licencia>
      <licencia>De obra</licencia>
      <licencia>Licencia comercial</licencia>
      <licencia>Licor</licencia>
      <licencia>Música</licencia>
    </licencias>
    <medidasPrevencion>
      <medida>extintores</medida>
      <medida>Plan de incendios</medida>
      <medida>Medidas higienicas</medida>
      <medida>Medidas de insonorizacion</medida>
      <medida>Alumbrado de emergencias</medida>
    </medidasPrevencion>
    <Empleados>
      <empleado>
        <nombreEmpleado>Paco</nombreEmpleado>
        <HorasTrabajadas>24</HorasTrabajadas>
        <tipoContrato>Temporal</tipoContrato>
      </empleado>
    </Empleados>
    <impuestos>
      <tipoImpuesto>IVA</tipoImpuesto>
    </impuestos>
    <socios>
      <socio>
        <nombreSocio>Juan</nombreSocio>
        <edad>40</edad>
        <porcentajeRetribuido>15</porcentajeRetribuido>
        <lugarNacimiento>Asturias</lugarNacimiento>
        <dni>87123098h</dni>
      </socio>
    </socios>
  </empresa>
  <datosempresario ISBN="3424789">
    <nombre>Erwin</nombre>
    <edad>50</edad>
    <pais>Alemania</pais>
    <lugarNacimiento>Berlin</lugarNacimiento>
    <dni>33484396k</dni>
  </datosempresario>
  <empresa>
    <nombreEmpresa>Cambia tu pieza</nombreEmpresa>
    <direccion>calle juan de austria</direccion>
    <tipoEstablecimiento>taller</tipoEstablecimiento>
    <antiguedad>1 año</antiguedad>
    <Nempleados>5</Nempleados>
    <ganancia>3456</ganancia>
    <licencias>
      <licencia>establ</licencia>
      <licencia>estable</licencia>
    </licencias>
    <medidasPrevencion>
      <medida>Plan de incendios</medida>
      <medida>Alumbrado de emergencias</medida>
    </medidasPrevencion>
    <Empleados>
      <empleado>
        <nombreEmpleado>Manolo</nombreEmpleado>
        <HorasTrabajadas>312</HorasTrabajadas>
        <edad>18</edad>
        <lugarNacimiento>Francia</lugarNacimiento>
        <tipoContrato>Indefinido</tipoContrato>
      </empleado>
      <empleado>
        <nombreEmpleado>Chedey</nombreEmpleado>
        <HorasTrabajadas>138</HorasTrabajadas>
        <edad>15</edad>
        <lugarNacimiento>Las Bahamas</lugarNacimiento>
        <tipoContrato>Parcial</tipoContrato>
      </empleado>
    </Empleados>
    <impuestos>
      <tipoImpuesto>IRPF</tipoImpuesto>
    </impuestos>
    <socios>
      <socio>
        <nombreSocio>Alejadro</nombreSocio>
        <edad>80</edad>
        <porcentajeRetribuido>45</porcentajeRetribuido>
        <lugarNacimiento>Galicia</lugarNacimiento>
        <dni>36475847y</dni>
      </socio>
      <socio>
        <nombreSocio>Javi</nombreSocio>
        <edad>34</edad>
        <porcentajeRetribuido>7</porcentajeRetribuido>
        <lugarNacimiento>Asturias</lugarNacimiento>
        <dni>36565847y</dni>
      </socio>
    </socios>
  </empresa>
</registro>
